# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Example.proto
"""Generated protocol buffer code."""
from simplebuf.google.protobuf.internal import builder as _builder
from simplebuf.google.protobuf import descriptor as _descriptor
from simplebuf.google.protobuf import descriptor_pool as _descriptor_pool
from simplebuf.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rExample.proto\")\n\rOption_Chains\x12\x18\n\x07\x45xample\x18\x01 \x03(\x0b\x32\x07.Option\"\xb4\x03\n\x06Option\x12\x0f\n\x07putCall\x18\x01 \x01(\t\x12\x17\n\x0fquoteTimeInLong\x18\x02 \x01(\x03\x12\x14\n\x0c\x65xchangeName\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x12\n\nunderlying\x18\x05 \x01(\t\x12\x10\n\x08\x62idPrice\x18\x06 \x01(\x01\x12\x10\n\x08\x61skPrice\x18\x07 \x01(\x01\x12\x0f\n\x07\x62idSize\x18\x08 \x01(\x03\x12\x0f\n\x07\x61skSize\x18\t \x01(\x03\x12\x12\n\nvolatility\x18\n \x01(\x01\x12\r\n\x05\x64\x65lta\x18\x0b \x01(\x01\x12\r\n\x05gamma\x18\x0c \x01(\x01\x12\r\n\x05theta\x18\r \x01(\x01\x12\x0c\n\x04vega\x18\x0e \x01(\x01\x12\x0b\n\x03rho\x18\x0f \x01(\x01\x12\x14\n\x0copenInterest\x18\x10 \x01(\x03\x12\x13\n\x0btotalVolume\x18\x11 \x01(\x03\x12\x16\n\x0e\x65xpirationDate\x18\x12 \x01(\t\x12\x18\n\x10\x64\x61ysToExpiration\x18\x13 \x01(\x03\x12\x13\n\x0bstrikePrice\x18\x14 \x01(\x01\x12\x17\n\x0funderlyingPrice\x18\x15 \x01(\x01\x12\x19\n\x11percentInTheMoney\x18\x16 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTION_CHAINS._serialized_start=17
  _OPTION_CHAINS._serialized_end=58
  _OPTION._serialized_start=61
  _OPTION._serialized_end=497
# @@protoc_insertion_point(module_scope)
